postgres:
  host: localhost
  port: 5432
  user: postgres
  password: 123456
  database: shanjuku
  timezone: Asia/Taipei
gin:
  address: localhost
  port: 6969
  isTls: false
  certificateFile: ""
  keyFile: ""
logger:
  level: info
  path: "./logs/"
  fileName: "shanjuku"
auth:
  jwtSecret: "to-do-shanjuku"
  passwordPrefix: "to-do-shanjuku"
