// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Group struct {
	ID      string `json:"id"`
	Account string `json:"account"`
	Name    string `json:"name"`
	Avatar  string `json:"avatar"`
}

type LoginInput struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type LoginPayload struct {
	ID    string `json:"id"`
	Token string `json:"token"`
}

type LogoutInput struct {
	Account string `json:"account"`
}

type LogoutPayload struct {
	Success bool `json:"success"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type RegisterPayload struct {
	ID    string `json:"id"`
	Token string `json:"token"`
}

type User struct {
	ID      string `json:"id"`
	Account string `json:"account"`
	Name    string `json:"name"`
	Avatar  string `json:"avatar"`
}
