// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitService() (*Service, error) {
	ginService := ProvideGinService()
	postgresService, err := ProvidePostgreService()
	if err != nil {
		return nil, err
	}
	service := ProvideService(ginService, postgresService)
	return service, nil
}

// wire.go:

var serviceSet = wire.NewSet(ProvideGinService, ProvidePostgreService, ProvideService)
